#!/bin/bash
yaourt -S localepurge compton-git ttf-opensans engrampa-thunar elementary-xfce-icons speedtest-cli profile-cleaner yad xfce-theme-greybird light-locker-settings ttf-ms-fonts ttf-roboto pamac-aur obkey-git mugshot ob-autostart blueman-git chromium-pepper-flash

#some files may fail
#download manually from the AUR
#future updates may be on SourceForge
