#!/bin/bash
sudo pacman -S haveged
sudo systemctl enable haveged
sudo systemctl start haveged
sudo pacman-key --init
sudo pacman-key --populate archlinux
sudo pacman -Syy

sudo pacman -S asciidoc archlinux-xdg-menu activity-log-manager accountsservice hwinfo flashplugin gmrun nitrogen parcellite tumbler gstreamer0.10-good-plugins chromium numlockx openbox oblogout obconf python2-xdg xfce4-terminal xfce4-screenshooter light-locker lxtask lxpanel leafpad pulseaudio pulseaudio-alsa pavucontrol gparted gpicview gpointing-device-settings gnome-ppp gnome-screensaver gnome-keyring arandr lxrandr lxpanel lxsession plank libcanberra-pulse lxappearance-obconf thunar thunar-archive-plugin thunar-volman networkmanager network-manager-applet xdg-user-dirs-gtk dosfstools ntfs-3g gvfs gamin p7zip unzip zip unrar wifi-radar wget xfce4-power-manager vala xorg-xkill xorg-xprop lightdm lightdm-gtk-greeter zeitgeist --noconfirm

xdg-user-dirs-update
sudo updatedb

sudo systemctl enable NetworkManager
sudo systemctl enable lightdm
sudo systemctl enable accounts-daemon
